import { Poppins } from "next/font/google";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import "./globals.css";

const poppins = Poppins({ weight: ["400", "500", "600", "700"], subsets: ["latin"], display:"swap" });

export const metadata = {
  title: "Nosara Booking Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={poppins.className} lang="en">
      <body>
          <Header />
          {children}
          <Footer />
      </body>
    </html>
  );
}